### ISSUE TITLE
Should scoping path in profile.yml be moved to referencing profile

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1583]
The SNIA "Enhanced Zoning and Enhanced Zoning Control" profile has two scoping paths.

Its profile definition in profiles.yml:

```
  registered_org: SNIA
  registered_name: Enhanced Zoning and Enhanced Zoning Control
  type: component
  central_class: CIM_ZoneService
  scoping_class: CIM_AdminDomain
  scoping_path:
    - CIM_HostedService
  # scoping_path2:
  #   - CIM_HostedService
  #   - CIM_ComputerSystem
  #   - CIM_Component
  doc: SMI-S Fabric
```

This case shows that the scoping path logically belongs more to the referencing profile than to the referenced profile.

**Discussion point:** Should we attach the definition of the scoping path to the profile references in the scoping profiles? 

That would require representing these references in profiles.yml (which we don't, currently).
