### ISSUE TITLE
_recorder and things like property names have case errors

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#597]
When we generate yaml with the recorder and then try to use it, we get a number of minor errors in the http comparisons because the names in the pywbem_request and pywbem_response items are lower case but what is in the http is mixed case.

For example:
```
  <CIM CIMVERSION="2.0" DTDVERSION="2.0">
    <MESSAGE ID="1001" PROTOCOLVERSION="1.0">
      <SIMPLEREQ>
        <IMETHODCALL NAME="References">
          <LOCALNAMESPACEPATH>
            <NAMESPACE NAME="root"></NAMESPACE>
            <NAMESPACE NAME="cimv2"></NAMESPACE>
          </LOCALNAMESPACEPATH>
          <IPARAMVALUE NAME="ObjectName">
            <INSTANCENAME CLASSNAME="PyWBEM_Person">
              <KEYBINDING NAME="CreationClassName (got: creationclassname)">
                <KEYVALUE VALUETYPE="string">PyWBEM_Person</KEYVALUE>
              </KEYBINDING>
              <KEYBINDING NAME="Name (got: name)">
                <KEYVALUE VALUETYPE="string">Alice</KEYVALUE>
```
This is because the recorder generates the yaml with lower case names for these things:
```
  pywbem_response:
    result:
    - pywbem_object: CIMInstance
      classname: PyWBEM_MemberOfPersonCollection
      properties:
        member:
          pywbem_object: CIMProperty
          name: Member
          value:
            pywbem_object: CIMInstanceName
            classname: PyWBEM_Person
            namespace: null
            keybindings:
              creationclassname: PyWBEM_Person
              name: Alice
```

Also we are getting other issues with operation parameters like the following in the recorder output:

      Role: null
      ResultClass: PyWBEM_MemberOfPersonCollection
      role: member

What we appear to be getting is the keybindings names in lower case in the recorder output for the
operation.  This then conflicts with the HTTP which has the correct case:
```
    operation:
      pywbem_method: AssociatorNames
      ResultClass: CIM_Collection
      Role: member
      AssocClass: PyWBEM_MemberOfPersonCollection
      ObjectName:
        pywbem_object: CIMInstanceName
        classname: PyWBEM_Person
        namespace: root/cimv2
        keybindings:
          creationclassname: PyWBEM_Person
          name: Alice
      ResultRole: Collection

      <IPARAMVALUE NAME="ObjectName">
      <INSTANCENAME CLASSNAME="PyWBEM_Person">
      <KEYBINDING NAME="CreationClassName">
      <KEYVALUE VALUETYPE="string">PyWBEM_Person</KEYVALUE>
      </KEYBINDING>
      <KEYBINDING NAME="Name">
      <KEYVALUE VALUETYPE="string">Alice</KEYVALUE>
      </KEYBINDING>
```

Also, at least for the associatorNames, the host is not included in the recorder output:
```
  pywbem_response:
    result:
    - pywbem_object: CIMInstanceName
      classname: PyWBEM_PersonCollection
      namespace: root/cimv2
      keybindings:
        instanceid: PersonCollection
```

but is in the http response:

```
      <IMETHODRESPONSE NAME="AssociatorNames">
      <IRETURNVALUE>
      <OBJECTPATH>
      <INSTANCEPATH>
      <NAMESPACEPATH>
      <HOST>sheldon</HOST>
      <LOCALNAMESPACEPATH>
      <NAMESPACE NAME="root"/>
      <NAMESPACE NAME="cimv2"/>
```
