### ISSUE TITLE
recorder sets return type for openassociators to result, not p

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#601]
I believe this is a duplicate of #648 in that they both cover the issues between pull results and results on the yaml.  

The recorder sets the return  type for open, and other pull operations to result where the required type is pullresult and shows the context items  wrong.

```
  pywbem_response:
    result:
    - - pywbem_object: CIMInstance
        classname: PyWBEM_PersonCollection
        properties:
          instanceid:
            pywbem_object: CIMProperty
            name: InstanceID
            value: PersonCollection
            type: string
            reference_class: null
            embedded_object: null
            is_array: false
            array_size: null
            class_origin: null
            propagated: null
            qualifiers: {}
          caption:
            pywbem_object: CIMProperty
            name: Caption
            value: null
            type: string
            reference_class: null
            embedded_object: null
            is_array: false
            array_size: null
            class_origin: null
            propagated: true
            qualifiers: {}
          elementname:
            pywbem_object: CIMProperty
            name: ElementName
            value: null
            type: string
            reference_class: null
            embedded_object: null
            is_array: false
            array_size: null
            class_origin: null
            propagated: true
            qualifiers: {}
          description:
            pywbem_object: CIMProperty
            name: Description
            value: null
            type: string
            reference_class: null
            embedded_object: null
            is_array: false
            array_size: null
            class_origin: null
            propagated: true
            qualifiers: {}
        path:
          pywbem_object: CIMInstanceName
          classname: PyWBEM_PersonCollection
          namespace: root/cimv2
          keybindings:
            instanceid: PersonCollection
    - false
    - - '500028'
      - root/cimv2
```
